"""Shared reply-keyboard labels."""

BTN_GIFT = "🎁 دریافت فایل‌های هدیه"
BTN_SUPPORT = "💬 پشتیبانی"
BTN_STATS = "📊 گزارش ربات"
BTN_MANAGE = "⚙️ مدیریت منو"
BTN_SKIP = "رد شدن"
BTN_CANCEL = "انصراف"
BTN_BACK = "↩️ بازگشت"
LEGACY_WEBINAR_BTN = "🔗 دریافت لینک وبینار"
